@echo off
echo Deleting dev-dist...
rmdir /s /q dev-dist 2>nul
echo Pulling changes...
git pull
echo Adding changes...
git add .
echo Committing...
git commit -m "Finalizacion SaaS: Tasa BCV dinamica, gestion PENDING_CASH y ajustes de soporte"
echo Pushing...
git push
